spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    data: classpath:/sql/data.sql
    schema: classpath:/sql/schema.sql
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    platform: H2
    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
